### ISSUE TITLE
Readme is misleading about udsoncan

### ISSUE THREAD

**Issue by pylessard** [mdabrowski1990/uds#288]
Hey,
Your readme says that python-udsoncan is an alternative and list a series of "cons" that are not true

> only positive use case scenarios (where communication is in line with UDS standard) are supported

That doesn't mean much. The library reports correctly any error. It is also possible to generate custom requests/response.    

> only CAN bus is supported

False. The underlying channel is fully abstracted. There is already the adapter to talk to queues, sockets. It's extensible

> only Client side communication can be handled

Half true, but ok.

> limited communication parameters configuration

Like what? Like I said, the underlying communication is abstracted. Comm parameters depends on the lower layers.  I also have an isotp package with all the possible parameters.

Would appreciate if you could correct.

**Comment by mdabrowski1990** [comment]
Thanks for feedback. I will gladly update it accordingly to your remarks.
