### ISSUE TITLE
Live chats

### ISSUE THREAD

**Issue by mdabrowski1990** [mdabrowski1990/uds#84]
## Description
As a user, I would like to have a chance for private discussion of security relevant topics.
As a developer, I would like to have information where I could have live chat, so I could discuss all kind of development topics, share my screen for pair programmign etc.

Discord server link: https://discord.gg/XYhJGeBg

## Acceptance Criteria
- [User documentation](https://uds.readthedocs.io/) is udpated with [link to discord server](https://discord.gg/XYhJGeBg).
- [Security policy](https://github.com/mdabrowski1990/uds/blob/main/SECURITY.md) is updated to have information about private discussion on discord.
- [ReadMe](https://github.com/mdabrowski1990/uds#readme) file is updated
- The server is properly configured:
  - Special area for security relevant topics that cannot be shared publicly
  - Restricted area for development discussions
  - Open area for guests and all kind of topics unrelated to the development

**Comment by mdabrowski1990** [comment]
Server was created link: https://discord.gg/7VCybgpf
Notifications (via webhooks) were provided.

**Comment by tomstano** [comment]
Hello, could you update the discord invitation? :)

**Comment by mdabrowski1990** [comment]
Hi   This is the proper link:  discord.gg discord.gg  Thanks for letting me know. I have just noticed it yesterday. The link I used before expired (it was valid for a week - my mistake). I have just added a new link (without an expiration date), but the change is on a branch (with different changes too) at the moment -  github.com github.com  It will be merged this week. Meanwhile, you can use the link that I have sent you.   Best regards  Maciej Dąbrowski   
            
          
     
      
       
        Dnia 20 września 2021 10:02 Tomasz Stano ***@***.***&gt; napisał(a):
       
    
       
         
 Hello, could you update the discord invitation? :)
